### ISSUE TITLE
[12.0][CE] import_chart_accounts --> Error when validating invoices

### ISSUE THREAD

**Issue by HaraldPanten** [QubiQ/qu-server-tools#1]
@xavierjimenez

Hi,

A change should be applied to import_chart_accounts module due to new version of Odoo base V12.

Find attached the following screenshot

![captura de pantalla 2018-12-19 a las 13 47 19](https://user-images.githubusercontent.com/32449357/50221211-bcdaa680-0394-11e9-95f0-54460b47e05e.png)

**Comment by chusamo** [comment]
Finally we fix this issue, thank you guys!
